# Generated by Django 5.1 on 2024-08-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='terminal_admin',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('busno', models.CharField(max_length=10)),
                ('iterm', models.CharField(max_length=30)),
                ('fterm', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
