# Generated by Django 5.1 on 2024-08-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Data',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('busno', models.CharField(max_length=10)),
                ('iterm', models.CharField(max_length=30)),
                ('fterm', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('goingtime', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='terminal_admin',
            name='busno',
        ),
        migrations.RemoveField(
            model_name='terminal_admin',
            name='fterm',
        ),
    ]
