# Generated by Django 5.1 on 2024-08-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_driver_data_remove_terminal_admin_busno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_data',
            name='finaltime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver_data',
            name='leavetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver_data',
            name='reachtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
