# Generated by Django 5.1 on 2024-08-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_driver_data_finaltime_driver_data_leavetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atend',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('name_p', models.BooleanField(default=True)),
                ('busno', models.CharField(max_length=10)),
                ('bus_p', models.BooleanField(default=False)),
                ('iterm', models.CharField(max_length=30)),
                ('fterm', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('goingtime', models.TimeField()),
                ('reachtime', models.TimeField(blank=True, null=True)),
                ('leavetime', models.TimeField(blank=True, null=True)),
                ('finaltime', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
