# Generated by Django 5.1 on 2024-08-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_atend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atend',
            name='name_p',
            field=models.BooleanField(default=False),
        ),
    ]
