# Generated by Django 5.1 on 2024-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_atend_name_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atend',
            name='bus_p',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atend',
            name='name_p',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
